apiVersion: v1
kind: PersistentVolume
metadata:
  # any PV name
  name: flask-pv
spec:
  storageClassName: flask001
  capacity:
    # storage size
    storage: 10Gi
  accessModes:
    # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    # retain even if pods terminate
    Retain
  nfs:
    # NFS server's definition
    path: /mnt/flask
    server: 192.168.14.11
    readOnly: false
